version: '3.9'

services:
  pokemon-api:
    build: .
    container_name: pokemon-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped